apiVersion: v1
kind: Secret
metadata:
  name: mysql-secret
type: Opaque
data: 
  mysql-username: YWRtaW4= # echo admin | base64, to decode, echo YWRtaW4= | base64 --decode
  mysql-password: MTIz
  mysql-root-password: MTIz
  mysql-database: dGVzdA==
